Mongo:
  #  URL: "mongodb://duobei:RZmongo4cPRqq5@134.175.253.100:30027/datacenter?authSource=admin"
  URL: "mongodb://127.0.0.1:27017/datacenter?authSource=admin"
  # MongoURL: "mongodb://report:3270815cb@dds-2ze494fdab7efbe4153t4-pub.mongodb.rds.aliyuncs.com:3717/duobei"
  hostname: "mongodb://duobei:UT87Pl%40ti%40xfRRE@134.175.253.100:27017/duobei?authSource=admin" # 原始数据仓库


Kafka:
  Addr: ["127.0.0.1:9092"]
  #  Ver: "2.0.1"
  Topics: ["streamtopic"]
  GroupId: "consumer-09"
  Offset: "earliest"

Mysql:
  user: "root"
  pwd: "209243"
  host: "127.0.0.1"
#  host: "42.192.178.84"
  port: 3306
  database: "us_congress"

Redis:
  host: "42.192.178.84"
  pwd: "209243"
  port: 6379
  database: 0